# Generated by Django 2.1.7 on 2019-03-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='countries',
            field=models.ManyToManyField(blank=True, to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='regions',
            field=models.ManyToManyField(blank=True, to='cities_light.Region'),
        ),
    ]
