# Generated by Django 2.1.7 on 2019-04-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20190401_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='owner',
            new_name='tipper',
        ),
    ]
